FROM node:9.6.1 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install
npm install nodemon -g
COPY . /usr/src/app
EXPOSE 3000

# start app
CMD ["npm", "start"]
